/** Telegram voice/list bot. */
const store=new Map();
const NEW_NOTE_BTN="Новая заметка",DELETE_NOTE_BTN="Удалить заметку",DEFAULT_LIST="Входящие";
const CHAT="qwen/qwen3.8-27b",FALLBACK="openai/gpt-oss-20b";
const WHISPER=["whisper-large-v3-turbo","whisper-large-v3"];
const CHAT_URL="https://api.groq.com/openai/v1/chat/completions",TR_URL="https://api.groq.com/openai/v1/audio/transcriptions";
const prompt=`Ты помощник по спискам заметок. Отвечай строго одним JSON без markdown: {"action":"add"|"show"|"new_list"|"delete_last"|"delete_note"|"clear_list"|"rename_list"|"star_list"|"unstar_list"|"move_list_top"|"help","list":"string","new_name":"string","note":"string","index":null|number,"query":"string"}.
Правила: add добавляет note; show показывает list или Входящие; new_list создаёт пустой list; delete_last удаляет последнюю заметку; delete_note удаляет одну по index (с 1) или query; clear_list только при явной просьбе очистить весь list; rename_list: list старое имя, new_name новое; star_list/unstar_list управляют избранным; move_list_top поднимает list наверх своей группы. Не выдумывай заметки. Для add без списка используй Входящие. Пиши значения по-русски.
Для note при add исправляй только пунктуацию, не меняй смысл и не добавляй слова: точка в конце предложения, запятые в перечислениях, вопросительный/восклицательный знак только по тону, имена списков в note не тащи, одну мысль не разбивай.`;
const token=()=>process.env.TELEGRAM_BOT_TOKEN||"", key=()=>process.env.GROQ_API_KEY||"";
function state(id){let s=store.get(String(id));if(!s){s={lists:{[DEFAULT_LIST]:[]},order:[DEFAULT_LIST],starred:[],step:null,pending:null,warn:false};store.set(String(id),s)};s.order=s.order.filter(n=>Array.isArray(s.lists[n]));for(const n of Object.keys(s.lists))if(!s.order.includes(n))s.order.push(n);if(!s.lists[DEFAULT_LIST]){s.lists[DEFAULT_LIST]=[];s.order.unshift(DEFAULT_LIST)};s.starred=s.starred.filter(n=>s.lists[n]);return s}
async function tg(method,body){if(!token())throw Error("no_token");const r=await fetch(`https://api.telegram.org/bot${token()}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.description||`telegram_${r.status}`);return d}
async function tgGet(method,q){const r=await fetch(`https://api.telegram.org/bot${token()}/${method}?${new URLSearchParams(q||{})}`),d=await r.json();if(!r.ok||d.ok===false)throw Error(d.description||`telegram_${r.status}`);return d}
const esc=x=>String(x).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"),star=(s,n)=>s.starred.includes(n),names=s=>{const a=s.order.filter(n=>s.lists[n]),f=a.filter(n=>star(s,n)),r=a.filter(n=>!star(s,n));return f.concat(r)},ensure=(s,n)=>{n=(n||DEFAULT_LIST).trim()||DEFAULT_LIST;if(!s.lists[n])s.lists[n]=[];if(!s.order.includes(n))s.order.push(n);return n};
function kb(s){const ns=names(s),rows=[[{text:NEW_NOTE_BTN},{text:DELETE_NOTE_BTN}]];for(let i=0;i<ns.length;i+=2)rows.push([{text:(star(s,ns[i])?"★ ":"")+ns[i]},{...(ns[i+1]?[{text:(star(s,ns[i+1])?"★ ":"")+ns[i+1]}]:[])}]);return{keyboard:rows,resize_keyboard:true,is_persistent:true,one_time_keyboard:false}}
function listText(s,n){const a=s.lists[n]||[];return `«${esc(star(s,n)?"★ "+n:n)}»:`+(a.length?"\n"+a.map((x,i)=>`${i+1}. ${esc(x)}`).join("\n"):" пусто.")}
function snapshot(s){return names(s).map(n=>`— ${star(s,n)?"★ ":""}${n}:`+(s.lists[n].length?"\n"+s.lists[n].map((x,i)=>`  ${i+1}. ${x}`).join("\n"):" (пусто)")).join("\n")}
async function send(id,text,s){return tg("sendMessage",{chat_id:id,text,parse_mode:"HTML",reply_markup:kb(s),})}
async function intent(text,s,hint=""){const body=`${hint?"Контекст: "+hint+"\n\n":""}Текущие списки:\n${snapshot(s)}\n\nСообщение пользователя:\n${text}`;let r=await fetch(CHAT_URL,{method:"POST",headers:{Authorization:"Bearer "+key(),"content-type":"application/json"},body:JSON.stringify({model:CHAT,temperature:.2,response_format:{type:"json_object"},messages:[{role:"system",content:prompt},{role:"user",content:body}]})});if(r.status===404)r=await fetch(CHAT_URL,{method:"POST",headers:{Authorization:"Bearer "+key(),"content-type":"application/json"},body:JSON.stringify({model:FALLBACK,temperature:.2,response_format:{type:"json_object"},messages:[{role:"system",content:prompt},{role:"user",content:body}]})});if(!r.ok)throw Error("chat_failed");const d=await r.json(),x=JSON.parse(d.choices?.[0]?.message?.content||"{}");return{action:["add","show","new_list","delete_last","delete_note","clear_list","rename_list","star_list","unstar_list","move_list_top","help"].includes(x.action)?x.action:"help",list:String(x.list||"").trim(),new_name:String(x.new_name||"").trim(),note:String(x.note||"").trim(),query:String(x.query||"").trim(),index:x.index==null?null:Number(x.index)}}
async function transcribe(fileId){const m=await tgGet("getFile",{file_id:fileId}),p=m.result.file_path,r=await fetch(`https://api.telegram.org/file/bot${token()}/${p}`);if(!r.ok)throw Error("voice_http_"+r.status);const b=await r.arrayBuffer(),f=new FormData(),name="voice.ogg";f.append("file",new Blob([b],{type:"audio/ogg"}),name);f.append("response_format","json");for(const model of WHISPER){f.set("model",model);f.set("language","ru");let q=await fetch(TR_URL,{method:"POST",headers:{Authorization:"Bearer "+key()},body:f});if(q.status===400){f.delete("language");q=await fetch(TR_URL,{method:"POST",headers:{Authorization:"Bearer "+key()},body:f})}if(q.ok){const d=await q.json();if(d.text)return String(d.text).trim()}}throw Error("transcribe_failed")}
async function apply(id,s,x){let n,a,i;if(x.action==="help")return send(id,"Пришлите голосовое или текст. Можно добавлять, показывать, удалять, переименовывать, добавлять список в избранное и поднимать его наверх.",s);if(x.action==="new_list"){n=ensure(s,x.list||"Новый список");return send(id,`Список «${esc(n)}» готов.`,s)}if(x.action==="show"){n=ensure(s,x.list);return send(id,listText(s,n),s)}if(x.action==="clear_list"){if(!x.list)return send(id,"Укажите имя списка для полной очистки.",s);n=ensure(s,x.list);a=s.lists[n].length;s.lists[n]=[];return send(id,`Очищен «${esc(n)}» (${a}).`,s)}if(x.action==="delete_last"){n=ensure(s,x.list);if(!s.lists[n].length)return send(id,`В «${esc(n)}» нечего удалять.`,s);return send(id,`Удалил из «${esc(n)}»: ${esc(s.lists[n].pop())}`,s)}if(x.action==="delete_note"){const q=(x.query||x.note).toLowerCase(),hits=[];for(const z of names(s)){a=s.lists[z];a.forEach((v,j)=>{if(x.index!=null?j===x.index-1:String(v).toLowerCase().includes(q))hits.push({n:z,j,v})})}if(hits.length!==1)return send(id,hits.length?"Нашёл несколько заметок — уточните номер или список.":"Не нашёл такую заметку.",s);const h=hits[0];s.lists[h.n].splice(h.j,1);return send(id,`Удалил из «${esc(h.n)}»: ${esc(h.v)}`,s)}if(x.action==="rename_list"){if(!s.lists[x.list])return send(id,`Списка «${esc(x.list)}» нет.`,s);if(!x.new_name||s.lists[x.new_name])return send(id,"Новое имя пустое или уже занято.",s);s.lists[x.new_name]=s.lists[x.list];delete s.lists[x.list];s.order=s.order.map(z=>z===x.list?x.new_name:z);s.starred=s.starred.map(z=>z===x.list?x.new_name:z);return send(id,`Переименовал «${esc(x.list)}» → «${esc(x.new_name)}».`,s)}if(x.action==="star_list"||x.action==="unstar_list"){if(!s.lists[x.list])return send(id,`Списка «${esc(x.list)}» нет.`,s);if(x.action==="star_list"&&!star(s,x.list))s.starred.push(x.list);if(x.action==="unstar_list")s.starred=s.starred.filter(z=>z!==x.list);return send(id,`${x.action==="star_list"?"★ Добавил в избранное":"Убрал ★ с"} «${esc(x.list)}».`,s)}if(x.action==="move_list_top"){if(!s.lists[x.list])return send(id,`Списка «${esc(x.list)}» нет.`,s);const f=star(s,x.list),a=s.order.filter(z=>z!==x.list),g=a.filter(z=>star(s,z)),r=a.filter(z=>!star(s,z));(f?g:r).unshift(x.list);s.order=g.concat(r);return send(id,`Поднял «${esc(x.list)}» наверх.`,s)}n=ensure(s,x.list);if(!x.note)return send(id,"Не понял текст заметки.",s);s.lists[n].push(x.note);return send(id,`Добавил в «${esc(n)}»: ${esc(x.note)}`,s)}
async function message(m){if(!m?.chat)return;const id=m.chat.id,s=state(id),t=(m.text||"").trim();if(t==="/start")return send(id,"Пришлите голосовое или текст.",s);if(t==="/cancel"){s.step=null;return send(id,"Ок, отменил.",s)}if(t===NEW_NOTE_BTN){s.step="note";return send(id,"Пришлите голосовое или текст для заметки.",s)}if(t===DELETE_NOTE_BTN){s.step="delete";return send(id,"Что удалить? Название, номер или часть текста.",s)}if(t){const n=names(s).find(z=>z===t||`★ ${z}`===t);if(n)return send(id,listText(s,n),s)}if(m.voice||m.audio){if(!key())return send(id,"Сервис временно недоступен: не настроен ключ Groq.",s);return apply(id,s,await intent(await transcribe(m.voice?.file_id||m.audio?.file_id),s,s.step==="delete"?"пользователь удаляет заметку":""))}if(t){if(!key())return send(id,"Сервис временно недоступен: не настроен ключ Groq.",s);return apply(id,s,await intent(t,s,s.step==="delete"?"пользователь удаляет заметку":""))}}
module.exports=async(req,res)=>{res.setHeader("Access-Control-Allow-Origin","*");if(req.method==="OPTIONS")return res.status(204).end();if(req.method==="GET"){if(!token())return res.status(503).json({ok:false,error:"no_token"});try{return res.status(200).json({ok:true,webhook:process.env.WEBHOOK_URL||"https://voice-lists-ten.vercel.app/api/bot",telegram:await tg("setWebhook",{url:process.env.WEBHOOK_URL||"https://voice-lists-ten.vercel.app/api/bot",allowed_updates:["message"],drop_pending_updates:false}),hasGroq:Boolean(key())})}catch(e){return res.status(500).json({ok:false,error:String(e.message||e)})}}if(req.method!=="POST")return res.status(405).json({ok:false,error:"method_not_allowed"});if(!token())return res.status(503).json({ok:false,error:"no_token"});try{if(req.body?.message)await message(req.body.message);return res.status(200).json({ok:true})}catch(e){return res.status(200).json({ok:false,error:String(e.message||e)})}};