/**
 * Telegram webhook: /api/bot
 * Env: TELEGRAM_BOT_TOKEN, GROQ_API_KEY, WEBHOOK_URL (optional),
 *      SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY (server only — never in Git/HTML)
 * Lists/notes persist in Supabase; step/pendingDeletes/warnedEphemeral stay in RAM.
 */

/** Ephemeral per-chat UI state only (not lists/notes). */
const ephemeral = new Map();

/** /start, /start@bot, /start payload — same for other cmds */
function isBotCommand(text, cmd) {
  const t = String(text || "").trim();
  return t === cmd || t.startsWith(cmd + " ") || t.startsWith(cmd + "@");
}

const NEW_NOTE_BTN = "Новая заметка";
const DELETE_NOTE_BTN = "Удалить заметку";
const DEFAULT_LIST = "Стикеры";
const LEGACY_DEFAULT = "Входящие";
const MAX_KB_BTN = 64;

const CHAT_PRIMARY = "qwen/qwen3.8-27b";
const CHAT_FALLBACK = "openai/gpt-oss-20b";
const WHISPER_MODELS = ["whisper-large-v3-turbo", "whisper-large-v3"];

const GROQ_CHAT_URL = "https://api.groq.com/openai/v1/chat/completions";
const GROQ_TRANSCRIBE_URL =
  "https://api.groq.com/openai/v1/audio/transcriptions";

const SYSTEM_PROMPT = `Ты помощник по спискам заметок. Ответь СТРОГО одним JSON-объектом без markdown:
{"action":"add"|"show"|"new_list"|"delete_last"|"delete_note"|"clear_list"|"rename_list"|"star_list"|"unstar_list"|"move_list_top"|"help","list":"string","new_name":"string","note":"string","index":null|number,"query":"string"}

Правила:
- action=add — добавить заметку; note обязателен.
- action=show — показать список; list если назван, иначе «Стикеры».
- action=new_list — создать пустой список с именем list.
- action=delete_last — удалить ПОСЛЕДНЮЮ заметку в list (если list не назван — «Стикеры»).
- action=delete_note — удалить ОДНУ заметку: index (номер с 1) и/или query (кусок текста); list если указан.
- action=clear_list — ТОЛЬКО если явно просят очистить весь список; list обязателен.
- action=rename_list — переименовать: list = старое имя, new_name = новое («переименуй X в Y», «назови X Y»).
- action=star_list — добавить список в избранное («X в избранное», «звезда на X»).
- action=unstar_list — убрать из избранного («убери звезду с X»).
- action=move_list_top — поднять список наверх своей группы («подними X», «X наверх»).
- action=help — если неясно.
- Не выдумывай заметки, которых нет в контексте списков.
- Если список не назван для add — list = «Стикеры».
- Пиши list/new_name/note/query на русском.

Пунктуация note (жёстко для action=add):
- Исправь пунктуацию, НЕ меняя смысл и НЕ выдумывая слова.
- Точка в конце предложения; запятые в перечислениях; не заменяй все запятые на «и».
- Вопросительный/восклицательный знак — только если по тону фразы ясно.
- Имена списков в note НЕ тащи.
- Одну мысль не раздувай в абзацы; одна короткая фраза-заметка.`;

const SCHEMA_SQL = `create table if not exists lists (
  chat_id text not null,
  name text not null,
  starred boolean not null default false,
  sort_order int not null default 0,
  primary key (chat_id, name)
);
create table if not exists notes (
  id bigint generated by default as identity primary key,
  chat_id text not null,
  list_name text not null,
  body text not null,
  created_at timestamptz not null default now()
);
create index if not exists notes_chat_list_idx on notes (chat_id, list_name, id);`;

let schemaAttempted = false;
let schemaOk = false;

function token() {
  return process.env.TELEGRAM_BOT_TOKEN || "";
}

function groqKey() {
  return process.env.GROQ_API_KEY || "";
}

function webhookPublicUrl() {
  return (
    process.env.WEBHOOK_URL ||
    "https://voice-lists-ten.vercel.app/api/bot"
  );
}

function supabaseUrl() {
  return String(process.env.SUPABASE_URL || "").replace(/\/$/, "");
}

function supabaseKey() {
  return process.env.SUPABASE_SERVICE_ROLE_KEY || "";
}

function supabaseConfigured() {
  return Boolean(supabaseUrl() && supabaseKey());
}

function sbHeaders(extra) {
  const key = supabaseKey();
  return Object.assign(
    {
      apikey: key,
      Authorization: "Bearer " + key,
      "Content-Type": "application/json",
      Prefer: "return=representation",
    },
    extra || {}
  );
}

async function sbRest(pathAndQuery, opts) {
  const base = supabaseUrl();
  if (!base || !supabaseKey()) {
    const err = new Error("no_supabase");
    throw err;
  }
  const method = (opts && opts.method) || "GET";
  const headers = sbHeaders(opts && opts.headers);
  const init = { method, headers };
  if (opts && opts.body != null) {
    init.body =
      typeof opts.body === "string" ? opts.body : JSON.stringify(opts.body);
  }
  const res = await fetch(base + pathAndQuery, init);
  const text = await res.text().catch(() => "");
  let data = null;
  if (text) {
    try {
      data = JSON.parse(text);
    } catch (_) {
      data = text;
    }
  }
  if (!res.ok) {
    const detail =
      (data && data.message) ||
      (data && data.error_description) ||
      (typeof data === "string" ? data.slice(0, 200) : "") ||
      "HTTP " + res.status;
    const err = new Error("supabase_" + res.status + ": " + detail);
    err.status = res.status;
    err.body = data;
    throw err;
  }
  return data;
}

async function tryRunSql(sql) {
  const base = supabaseUrl();
  const key = supabaseKey();
  if (!base || !key) return false;
  const attempts = [
    { path: "/pg/query", body: { query: sql } },
    { path: "/pg-meta/default/query", body: { query: sql } },
    { path: "/rest/v1/rpc/exec_sql", body: { query: sql } },
    { path: "/rest/v1/rpc/sql", body: { query: sql } },
  ];
  for (const a of attempts) {
    try {
      const res = await fetch(base + a.path, {
        method: "POST",
        headers: sbHeaders(),
        body: JSON.stringify(a.body),
      });
      if (res.ok) {
        await res.text().catch(() => "");
        return true;
      }
      await res.text().catch(() => "");
    } catch (_) {}
  }
  return false;
}

async function ensureSchema() {
  if (schemaAttempted) return schemaOk;
  schemaAttempted = true;
  if (!supabaseConfigured()) {
    schemaOk = false;
    return false;
  }
  schemaOk = await tryRunSql(SCHEMA_SQL);
  return schemaOk;
}

function getEph(chatId) {
  const key = String(chatId);
  if (!ephemeral.has(key)) {
    ephemeral.set(key, {
      step: null,
      pendingDeletes: null,
      warnedEphemeral: false,
    });
  }
  return ephemeral.get(key);
}

function syncEph(state) {
  const e = state._eph;
  e.step = state.step;
  e.pendingDeletes = state.pendingDeletes;
  e.warnedEphemeral = state.warnedEphemeral;
}

async function loadChat(chatId) {
  await ensureSchema();
  if (!supabaseConfigured()) {
    throw new Error("no_supabase");
  }
  const key = String(chatId);
  const eph = getEph(key);

  let listRows;
  let noteRows;
  try {
    listRows = await sbRest(
      "/rest/v1/lists?chat_id=eq." +
        encodeURIComponent(key) +
        "&select=*&order=sort_order.asc"
    );
    noteRows = await sbRest(
      "/rest/v1/notes?chat_id=eq." +
        encodeURIComponent(key) +
        "&select=id,list_name,body&order=id.asc"
    );
  } catch (err) {
    throw err;
  }
  if (!Array.isArray(listRows)) listRows = [];
  if (!Array.isArray(noteRows)) noteRows = [];

  const state = {
    chatId: key,
    lists: {},
    noteIds: {},
    order: [],
    starred: [],
    step: eph.step,
    pendingDeletes: eph.pendingDeletes,
    warnedEphemeral: eph.warnedEphemeral,
    _eph: eph,
  };

  for (const row of listRows) {
    const name = row.name;
    if (!name) continue;
    state.lists[name] = [];
    state.noteIds[name] = [];
    state.order.push(name);
    if (row.starred) state.starred.push(name);
  }

  for (const row of noteRows) {
    const ln = row.list_name;
    if (!ln) continue;
    if (!Array.isArray(state.lists[ln])) {
      state.lists[ln] = [];
      state.noteIds[ln] = [];
      if (!state.order.includes(ln)) state.order.push(ln);
    }
    state.lists[ln].push(row.body);
    state.noteIds[ln].push(row.id);
  }

  await migrateIncomingToStickersDb(state);
  await ensureDefaultListDb(state);
  return state;
}

async function ensureDefaultListDb(state) {
  if (!Array.isArray(state.lists[DEFAULT_LIST])) {
    state.lists[DEFAULT_LIST] = [];
    state.noteIds[DEFAULT_LIST] = [];
  }
  if (!state.order.includes(DEFAULT_LIST)) {
    state.order.unshift(DEFAULT_LIST);
  }
  const exists = await sbRest(
    "/rest/v1/lists?chat_id=eq." +
      encodeURIComponent(state.chatId) +
      "&name=eq." +
      encodeURIComponent(DEFAULT_LIST) +
      "&select=name"
  );
  if (!Array.isArray(exists) || !exists.length) {
    await sbRest("/rest/v1/lists", {
      method: "POST",
      headers: sbHeaders({
        Prefer: "return=representation,resolution=merge-duplicates",
      }),
      body: {
        chat_id: state.chatId,
        name: DEFAULT_LIST,
        starred: false,
        sort_order: 0,
      },
    });
  }
}

async function migrateIncomingToStickersDb(state) {
  if (!Object.prototype.hasOwnProperty.call(state.lists, LEGACY_DEFAULT)) {
    return;
  }
  const legacyNotes = state.lists[LEGACY_DEFAULT] || [];
  const legacyIds = state.noteIds[LEGACY_DEFAULT] || [];
  const legacyStarred = (state.starred || []).includes(LEGACY_DEFAULT);

  if (!Array.isArray(state.lists[DEFAULT_LIST])) {
    state.lists[DEFAULT_LIST] = [];
    state.noteIds[DEFAULT_LIST] = [];
  }

  // Move notes in DB
  if (legacyIds.length) {
    await sbRest(
      "/rest/v1/notes?chat_id=eq." +
        encodeURIComponent(state.chatId) +
        "&list_name=eq." +
        encodeURIComponent(LEGACY_DEFAULT),
      {
        method: "PATCH",
        body: { list_name: DEFAULT_LIST },
      }
    );
  }

  state.lists[DEFAULT_LIST] = state.lists[DEFAULT_LIST].concat(legacyNotes);
  state.noteIds[DEFAULT_LIST] = state.noteIds[DEFAULT_LIST].concat(legacyIds);
  delete state.lists[LEGACY_DEFAULT];
  delete state.noteIds[LEGACY_DEFAULT];

  // Ensure Стикеры list row, merge starred, drop legacy row
  const stickersExists = await sbRest(
    "/rest/v1/lists?chat_id=eq." +
      encodeURIComponent(state.chatId) +
      "&name=eq." +
      encodeURIComponent(DEFAULT_LIST) +
      "&select=name,starred,sort_order"
  );
  if (!Array.isArray(stickersExists) || !stickersExists.length) {
    await sbRest("/rest/v1/lists", {
      method: "POST",
      body: {
        chat_id: state.chatId,
        name: DEFAULT_LIST,
        starred: legacyStarred,
        sort_order: 0,
      },
    });
  } else if (legacyStarred && !stickersExists[0].starred) {
    await sbRest(
      "/rest/v1/lists?chat_id=eq." +
        encodeURIComponent(state.chatId) +
        "&name=eq." +
        encodeURIComponent(DEFAULT_LIST),
      { method: "PATCH", body: { starred: true } }
    );
  }

  await sbRest(
    "/rest/v1/lists?chat_id=eq." +
      encodeURIComponent(state.chatId) +
      "&name=eq." +
      encodeURIComponent(LEGACY_DEFAULT),
    { method: "DELETE", headers: sbHeaders({ Prefer: "return=minimal" }) }
  );

  state.order = (state.order || [])
    .map((n) => (n === LEGACY_DEFAULT ? DEFAULT_LIST : n))
    .filter((n, i, arr) => n && arr.indexOf(n) === i);
  if (!state.order.includes(DEFAULT_LIST)) state.order.unshift(DEFAULT_LIST);
  state.starred = (state.starred || [])
    .map((n) => (n === LEGACY_DEFAULT ? DEFAULT_LIST : n))
    .filter((n, i, arr) => n && arr.indexOf(n) === i && state.lists[n]);
}

async function dbInsertList(state, name, starred, sortOrder) {
  await sbRest("/rest/v1/lists", {
    method: "POST",
    headers: sbHeaders({
      Prefer: "return=representation,resolution=merge-duplicates",
    }),
    body: {
      chat_id: state.chatId,
      name,
      starred: Boolean(starred),
      sort_order: sortOrder == null ? state.order.length : sortOrder,
    },
  });
}

async function dbInsertNote(state, listName, body) {
  const rows = await sbRest("/rest/v1/notes", {
    method: "POST",
    body: {
      chat_id: state.chatId,
      list_name: listName,
      body,
    },
  });
  const row = Array.isArray(rows) ? rows[0] : rows;
  return row && row.id;
}

async function dbDeleteNoteById(state, noteId) {
  await sbRest(
    "/rest/v1/notes?id=eq." +
      encodeURIComponent(String(noteId)) +
      "&chat_id=eq." +
      encodeURIComponent(state.chatId),
    { method: "DELETE", headers: sbHeaders({ Prefer: "return=minimal" }) }
  );
}

async function dbClearNotes(state, listName) {
  await sbRest(
    "/rest/v1/notes?chat_id=eq." +
      encodeURIComponent(state.chatId) +
      "&list_name=eq." +
      encodeURIComponent(listName),
    { method: "DELETE", headers: sbHeaders({ Prefer: "return=minimal" }) }
  );
}

async function dbSetStarred(state, name, starred) {
  await sbRest(
    "/rest/v1/lists?chat_id=eq." +
      encodeURIComponent(state.chatId) +
      "&name=eq." +
      encodeURIComponent(name),
    { method: "PATCH", body: { starred: Boolean(starred) } }
  );
}

async function dbWriteSortOrders(state, orderNames) {
  // Sequential patches — PostgREST has no multi-row patch by different keys easily
  for (let i = 0; i < orderNames.length; i++) {
    await sbRest(
      "/rest/v1/lists?chat_id=eq." +
        encodeURIComponent(state.chatId) +
        "&name=eq." +
        encodeURIComponent(orderNames[i]),
      { method: "PATCH", body: { sort_order: i } }
    );
  }
}

async function dbRenameList(state, oldName, newName) {
  const conflict = await sbRest(
    "/rest/v1/lists?chat_id=eq." +
      encodeURIComponent(state.chatId) +
      "&name=eq." +
      encodeURIComponent(newName) +
      "&select=name"
  );
  if (Array.isArray(conflict) && conflict.length) {
    const err = new Error("name_taken");
    throw err;
  }
  // Update notes first, then list PK via delete+insert or patch name
  await sbRest(
    "/rest/v1/notes?chat_id=eq." +
      encodeURIComponent(state.chatId) +
      "&list_name=eq." +
      encodeURIComponent(oldName),
    { method: "PATCH", body: { list_name: newName } }
  );
  const oldRows = await sbRest(
    "/rest/v1/lists?chat_id=eq." +
      encodeURIComponent(state.chatId) +
      "&name=eq." +
      encodeURIComponent(oldName) +
      "&select=*"
  );
  const old = Array.isArray(oldRows) && oldRows[0] ? oldRows[0] : null;
  await sbRest("/rest/v1/lists", {
    method: "POST",
    headers: sbHeaders({
      Prefer: "return=representation,resolution=merge-duplicates",
    }),
    body: {
      chat_id: state.chatId,
      name: newName,
      starred: old ? Boolean(old.starred) : false,
      sort_order: old ? old.sort_order : 0,
    },
  });
  await sbRest(
    "/rest/v1/lists?chat_id=eq." +
      encodeURIComponent(state.chatId) +
      "&name=eq." +
      encodeURIComponent(oldName),
    { method: "DELETE", headers: sbHeaders({ Prefer: "return=minimal" }) }
  );
}

async function tg(method, body) {
  const t = token();
  if (!t) throw new Error("TELEGRAM_BOT_TOKEN is not set");
  const res = await fetch(`https://api.telegram.org/bot${t}/${method}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok || data.ok === false) {
    const msg =
      (data && data.description) || `Telegram ${method} HTTP ${res.status}`;
    throw new Error(msg);
  }
  return data;
}

async function tgGet(method, query) {
  const t = token();
  if (!t) throw new Error("TELEGRAM_BOT_TOKEN is not set");
  const qs = new URLSearchParams(query || {}).toString();
  const url =
    `https://api.telegram.org/bot${t}/${method}` + (qs ? "?" + qs : "");
  const res = await fetch(url);
  const data = await res.json().catch(() => ({}));
  if (!res.ok || data.ok === false) {
    const msg =
      (data && data.description) || `Telegram ${method} HTTP ${res.status}`;
    throw new Error(msg);
  }
  return data;
}

async function sendMessage(chatId, text, extra) {
  return tg("sendMessage", {
    chat_id: chatId,
    text,
    parse_mode: "HTML",
    ...extra,
  });
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function clipBtn(label) {
  const s = String(label || "");
  if (s.length <= MAX_KB_BTN) return s;
  return s.slice(0, MAX_KB_BTN - 1) + "…";
}

function isStarred(state, name) {
  return (state.starred || []).includes(name);
}

function displayListName(state, name) {
  return isStarred(state, name) ? "★ " + name : name;
}

function listNames(state) {
  const order = (state.order || []).filter((n) => state.lists && state.lists[n]);
  const starredSet = new Set(state.starred || []);
  const fav = order.filter((n) => starredSet.has(n));
  const rest = order.filter((n) => !starredSet.has(n));
  const names = fav.concat(rest);
  if (!names.includes(DEFAULT_LIST) && state.lists && state.lists[DEFAULT_LIST]) {
    if (starredSet.has(DEFAULT_LIST)) names.unshift(DEFAULT_LIST);
    else {
      const i = names.findIndex((n) => !starredSet.has(n));
      if (i < 0) names.push(DEFAULT_LIST);
      else names.splice(i, 0, DEFAULT_LIST);
    }
  }
  return names.filter((n, i, arr) => arr.indexOf(n) === i);
}

function ensureInOrder(state, name) {
  if (!state.order.includes(name)) state.order.push(name);
}

function keyboardFor(state) {
  const rows = [[{ text: NEW_NOTE_BTN }, { text: DELETE_NOTE_BTN }]];
  const names = listNames(state);
  for (let i = 0; i < names.length; i += 2) {
    const chunk = [{ text: clipBtn(displayListName(state, names[i])) }];
    if (names[i + 1]) {
      chunk.push({ text: clipBtn(displayListName(state, names[i + 1])) });
    }
    rows.push(chunk);
  }
  return {
    keyboard: rows,
    resize_keyboard: true,
    is_persistent: true,
    one_time_keyboard: false,
  };
}

async function kb(chatId) {
  try {
    const state = await loadChat(chatId);
    return keyboardFor(state);
  } catch (_) {
    return {
      keyboard: [[{ text: NEW_NOTE_BTN }, { text: DELETE_NOTE_BTN }]],
      resize_keyboard: true,
      is_persistent: true,
      one_time_keyboard: false,
    };
  }
}

function resolveListButton(state, text) {
  const raw = String(text || "").trim();
  const stripped = raw.replace(/^★\s*/, "");
  const names = listNames(state);
  for (const n of names) {
    if (n === raw || n === stripped) return n;
    if (clipBtn(n) === raw || clipBtn(n) === stripped) return n;
    if (clipBtn(displayListName(state, n)) === raw) return n;
    if (displayListName(state, n) === raw) return n;
  }
  return null;
}

function formatList(state, name, notes) {
  const title = displayListName(state, name);
  if (!notes.length) return "«" + escapeHtml(title) + "»: пусто.";
  const body = notes
    .map((n, i) => i + 1 + ". " + escapeHtml(n))
    .join("\n");
  return "«" + escapeHtml(title) + "»:\n" + body;
}

function clipShort(label, max) {
  const s = String(label || "");
  const m = max || 28;
  if (s.length <= m) return s;
  return s.slice(0, m - 1) + "…";
}

/** Inline grid only for default «Стикеры» list. */
function stickersInlineKeyboard(notes) {
  const rows = [];
  const n = notes.length;
  if (n <= 4) {
    for (let i = 0; i < n; i++) {
      rows.push([
        { text: clipBtn(notes[i]), callback_data: "sn:" + i },
      ]);
    }
  } else {
    for (let i = 0; i < n; i += 2) {
      const row = [
        { text: clipShort(notes[i], 28), callback_data: "sn:" + i },
      ];
      if (i + 1 < n) {
        row.push({
          text: clipShort(notes[i + 1], 28),
          callback_data: "sn:" + (i + 1),
        });
      }
      rows.push(row);
    }
  }
  return { inline_keyboard: rows };
}

async function showListMessage(chatId, state, name) {
  const notes = state.lists[name] || [];
  if (name === DEFAULT_LIST) {
    const title = displayListName(state, name);
    if (!notes.length) {
      await sendMessage(
        chatId,
        "«" + escapeHtml(title) + "»: пусто.",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    await sendMessage(chatId, "«" + escapeHtml(title) + "» — выберите стикер:", {
      reply_markup: stickersInlineKeyboard(notes),
    });
    return;
  }
  await sendMessage(chatId, formatList(state, name, notes), {
    reply_markup: keyboardFor(state),
  });
}

function listsSnapshot(state) {
  return listNames(state)
    .map((name) => {
      const notes = state.lists[name] || [];
      const label = displayListName(state, name);
      if (!notes.length) return "— " + label + ": (пусто)";
      return (
        "— " +
        label +
        ":\n" +
        notes.map((n, i) => "  " + (i + 1) + ". " + n).join("\n")
      );
    })
    .join("\n");
}

function findNoteMatches(state, listHint, query, index) {
  const q = String(query || "").trim().toLowerCase();
  const hasIndex = index != null && Number.isFinite(Number(index));
  const names =
    listHint && Array.isArray(state.lists[listHint])
      ? [listHint]
      : listNames(state);
  const hits = [];
  for (const name of names) {
    const notes = state.lists[name] || [];
    const ids = state.noteIds[name] || [];
    if (hasIndex) {
      const i = Number(index) - 1;
      if (i >= 0 && i < notes.length) {
        hits.push({ list: name, index: i, note: notes[i], id: ids[i] });
      }
      continue;
    }
    if (!q) continue;
    notes.forEach((note, i) => {
      if (String(note).toLowerCase().includes(q)) {
        hits.push({ list: name, index: i, note, id: ids[i] });
      }
    });
  }
  return hits;
}

async function ensureList(state, name) {
  let listName = (name && String(name).trim()) || DEFAULT_LIST;
  if (listName === LEGACY_DEFAULT) listName = DEFAULT_LIST;
  if (!Array.isArray(state.lists[listName])) {
    state.lists[listName] = [];
    state.noteIds[listName] = [];
    ensureInOrder(state, listName);
    await dbInsertList(state, listName, false, state.order.indexOf(listName));
  } else {
    ensureInOrder(state, listName);
  }
  return listName;
}

function dbFailMessage(err) {
  const code = String((err && err.message) || err);
  if (code === "no_supabase") {
    return (
      "Не удалось подключиться к базе данных Supabase. " +
      "На сервере не заданы SUPABASE_URL и/или SUPABASE_SERVICE_ROLE_KEY."
    );
  }
  if (code.startsWith("supabase_")) {
    return (
      "Ошибка базы данных Supabase (" +
      escapeHtml(code.slice(0, 80)) +
      "). Данные не сохранены."
    );
  }
  return "Ошибка сохранения: " + escapeHtml(code.slice(0, 120));
}

async function downloadVoice(fileId) {
  const meta = await tgGet("getFile", { file_id: fileId });
  const filePath = meta.result && meta.result.file_path;
  if (!filePath) throw new Error("no_file_path");
  const t = token();
  const url = `https://api.telegram.org/file/bot${t}/${filePath}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error("http_" + res.status);
  const buf = Buffer.from(await res.arrayBuffer());
  const extRaw = (filePath.split(".").pop() || "ogg").toLowerCase();
  const isOgg = extRaw === "oga" || extRaw === "ogg" || extRaw === "opus";
  const filename = isOgg ? "voice.ogg" : "voice." + extRaw;
  const mime = isOgg
    ? "audio/ogg"
    : extRaw === "mp3"
      ? "audio/mpeg"
      : extRaw === "m4a" || extRaw === "mp4" || extRaw === "mp4a"
        ? "audio/mp4"
        : "audio/ogg";
  return { buf, filename, mime };
}

async function transcribe(buf, filename, mime) {
  const key = groqKey();
  if (!key) {
    throw new Error("no_groq");
  }

  const bytes = buf instanceof Uint8Array ? buf : new Uint8Array(buf);
  const name = filename || "voice.ogg";
  const type = mime || "audio/ogg";
  let lastHttp = 0;

  for (const model of WHISPER_MODELS) {
    for (const withLang of [true, false]) {
      const form = new FormData();
      const file =
        typeof File !== "undefined"
          ? new File([bytes], name, { type })
          : new Blob([bytes], { type });
      form.append("file", file, name);
      form.append("model", model);
      form.append("response_format", "json");
      if (withLang) form.append("language", "ru");

      const res = await fetch(GROQ_TRANSCRIBE_URL, {
        method: "POST",
        headers: { Authorization: "Bearer " + key },
        body: form,
      });
      lastHttp = res.status;

      if (res.ok) {
        const data = await res.json().catch(() => ({}));
        const textOut = (data && data.text ? String(data.text) : "").trim();
        if (textOut) return textOut;
        if (withLang) continue;
        break;
      }

      await res.text().catch(() => "");

      if (res.status === 400 && withLang) {
        continue;
      }
      if (res.status === 404) {
        break;
      }
      break;
    }
  }

  throw new Error("http_" + (lastHttp || 0));
}

async function callChat(model, userText) {
  const key = groqKey();
  if (!key) throw new Error("no_groq");
  return fetch(GROQ_CHAT_URL, {
    method: "POST",
    headers: {
      Authorization: "Bearer " + key,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      temperature: 0.2,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: userText },
      ],
    }),
  });
}

function parseIntent(raw) {
  let text = String(raw || "").trim();
  if (text.startsWith("```")) {
    text = text.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
  }
  const data = JSON.parse(text);
  const action = String(data.action || "help").toLowerCase();
  const allowed = [
    "add",
    "show",
    "new_list",
    "delete_last",
    "delete_note",
    "clear_list",
    "rename_list",
    "star_list",
    "unstar_list",
    "move_list_top",
    "help",
  ];
  let index = null;
  if (data.index != null && data.index !== "") {
    const n = Number(data.index);
    if (Number.isFinite(n)) index = n;
  }
  return {
    action: allowed.includes(action) ? action : "help",
    list: typeof data.list === "string" ? data.list.trim() : "",
    new_name: typeof data.new_name === "string" ? data.new_name.trim() : "",
    note: typeof data.note === "string" ? data.note.trim() : "",
    query: typeof data.query === "string" ? data.query.trim() : "",
    index,
  };
}

async function interpret(userText, state, hint) {
  const snapshot = listsSnapshot(state);
  const payload =
    (hint ? "Контекст: " + hint + "\n\n" : "") +
    "Текущие списки:\n" +
    snapshot +
    "\n\nСообщение пользователя:\n" +
    userText;
  let res = await callChat(CHAT_PRIMARY, payload);
  if (res.status === 404) {
    res = await callChat(CHAT_FALLBACK, payload);
  }
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error("chat_failed");
  }
  const content =
    data.choices &&
    data.choices[0] &&
    data.choices[0].message &&
    data.choices[0].message.content;
  return parseIntent(content);
}

function helpText() {
  return (
    "Пришлите голосовое или текст.\n" +
    "Примеры: «в покупки купить фильтр», «покажи покупки», «удали молоко из покупок»,\n" +
    "«переименуй покупки в дела», «покупки в избранное», «подними покупки».\n" +
    "Кнопки внизу: новая заметка, удалить, и ваши списки (★ — избранные)."
  );
}

async function applyIntent(chatId, state, intent) {
  const action = intent.action;
  if (action === "help") {
    await sendMessage(chatId, helpText(), { reply_markup: keyboardFor(state) });
    return;
  }

  if (action === "new_list") {
    const name = await ensureList(state, intent.list || "Новый список");
    syncEph(state);
    await sendMessage(chatId, "Список «" + escapeHtml(name) + "» готов.", {
      reply_markup: keyboardFor(state),
    });
    return;
  }

  if (action === "show") {
    const name = await ensureList(state, intent.list || DEFAULT_LIST);
    await showListMessage(chatId, state, name);
    return;
  }

  if (action === "clear_list") {
    if (!intent.list) {
      await sendMessage(
        chatId,
        "Какой список очистить целиком? Напишите имя.",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    const name = await ensureList(state, intent.list);
    const n = (state.lists[name] || []).length;
    await dbClearNotes(state, name);
    state.lists[name] = [];
    state.noteIds[name] = [];
    syncEph(state);
    await sendMessage(
      chatId,
      "Очистил «" + escapeHtml(name) + "» (" + n + ").",
      { reply_markup: keyboardFor(state) }
    );
    return;
  }

  if (action === "delete_last") {
    const name = await ensureList(state, intent.list || DEFAULT_LIST);
    const notes = state.lists[name] || [];
    const ids = state.noteIds[name] || [];
    if (!notes.length) {
      await sendMessage(
        chatId,
        "В «" + escapeHtml(name) + "» нечего удалять.",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    const removed = notes[notes.length - 1];
    const removedId = ids[ids.length - 1];
    if (removedId != null) await dbDeleteNoteById(state, removedId);
    notes.pop();
    ids.pop();
    syncEph(state);
    await sendMessage(
      chatId,
      "Удалил из «" + escapeHtml(name) + "»: " + escapeHtml(removed),
      { reply_markup: keyboardFor(state) }
    );
    return;
  }

  if (action === "delete_note") {
    const listHint =
      intent.list && Array.isArray(state.lists[intent.list])
        ? intent.list
        : "";
    const query = intent.query || intent.note || "";
    const hits = findNoteMatches(
      state,
      listHint || null,
      query,
      intent.index
    );

    if (!hits.length) {
      await sendMessage(
        chatId,
        "Не нашёл такую заметку. Уточните номер, кусок текста или список.",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }

    if (hits.length > 1) {
      const options = hits.slice(0, 3);
      state.step = "await_delete_pick";
      state.pendingDeletes = options;
      syncEph(state);
      const lines = options
        .map(
          (h, i) =>
            i +
            1 +
            ") «" +
            escapeHtml(h.list) +
            "» #" +
            (h.index + 1) +
            ": " +
            escapeHtml(h.note)
        )
        .join("\n");
      await sendMessage(
        chatId,
        "Нашёл несколько. Какую удалить? Ответьте номером варианта:\n" +
          lines,
        { reply_markup: keyboardFor(state) }
      );
      return;
    }

    const hit = hits[0];
    const arr = state.lists[hit.list] || [];
    const ids = state.noteIds[hit.list] || [];
    if (arr[hit.index] !== hit.note) {
      await sendMessage(
        chatId,
        "Заметка уже изменилась. Покажите список и попробуйте ещё раз.",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    if (hit.id != null) await dbDeleteNoteById(state, hit.id);
    else if (ids[hit.index] != null) await dbDeleteNoteById(state, ids[hit.index]);
    arr.splice(hit.index, 1);
    ids.splice(hit.index, 1);
    state.step = null;
    state.pendingDeletes = null;
    syncEph(state);
    await sendMessage(
      chatId,
      "Удалил из «" +
        escapeHtml(hit.list) +
        "»: " +
        escapeHtml(hit.note),
      { reply_markup: keyboardFor(state) }
    );
    return;
  }

  if (action === "rename_list") {
    const oldName = (intent.list || "").trim();
    const newName = (intent.new_name || "").trim();
    if (!oldName || !newName) {
      await sendMessage(
        chatId,
        "Укажите старое и новое имя: «переименуй X в Y».",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    if (!Array.isArray(state.lists[oldName])) {
      await sendMessage(
        chatId,
        "Списка «" + escapeHtml(oldName) + "» нет — ничего не менял.",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    if (oldName === newName) {
      await sendMessage(
        chatId,
        "Имя то же самое — «" + escapeHtml(oldName) + "».",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    if (Array.isArray(state.lists[newName])) {
      await sendMessage(
        chatId,
        "Имя «" +
          escapeHtml(newName) +
          "» уже занято — не затирал. Выберите другое.",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    try {
      await dbRenameList(state, oldName, newName);
    } catch (err) {
      if (String(err && err.message) === "name_taken") {
        await sendMessage(
          chatId,
          "Имя «" +
            escapeHtml(newName) +
            "» уже занято — не затирал. Выберите другое.",
          { reply_markup: keyboardFor(state) }
        );
        return;
      }
      throw err;
    }
    state.lists[newName] = state.lists[oldName];
    state.noteIds[newName] = state.noteIds[oldName];
    delete state.lists[oldName];
    delete state.noteIds[oldName];
    state.order = state.order.map((n) => (n === oldName ? newName : n));
    state.starred = state.starred.map((n) => (n === oldName ? newName : n));
    syncEph(state);
    await sendMessage(
      chatId,
      "Переименовал «" +
        escapeHtml(oldName) +
        "» → «" +
        escapeHtml(newName) +
        "».",
      { reply_markup: keyboardFor(state) }
    );
    return;
  }

  if (action === "star_list") {
    const name = (intent.list || "").trim();
    if (!name || !Array.isArray(state.lists[name])) {
      await sendMessage(
        chatId,
        name
          ? "Списка «" + escapeHtml(name) + "» нет."
          : "Какой список в избранное?",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    await dbSetStarred(state, name, true);
    if (!isStarred(state, name)) state.starred.push(name);
    syncEph(state);
    await sendMessage(
      chatId,
      "★ «" + escapeHtml(name) + "» в избранном.",
      { reply_markup: keyboardFor(state) }
    );
    return;
  }

  if (action === "unstar_list") {
    const name = (intent.list || "").trim();
    if (!name || !Array.isArray(state.lists[name])) {
      await sendMessage(
        chatId,
        name
          ? "Списка «" + escapeHtml(name) + "» нет."
          : "С какого списка убрать звезду?",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    await dbSetStarred(state, name, false);
    state.starred = state.starred.filter((n) => n !== name);
    syncEph(state);
    await sendMessage(
      chatId,
      "Убрал ★ с «" + escapeHtml(name) + "».",
      { reply_markup: keyboardFor(state) }
    );
    return;
  }

  if (action === "move_list_top") {
    const name = (intent.list || "").trim();
    if (!name || !Array.isArray(state.lists[name])) {
      await sendMessage(
        chatId,
        name
          ? "Списка «" + escapeHtml(name) + "» нет."
          : "Какой список поднять?",
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
    ensureInOrder(state, name);
    const starred = isStarred(state, name);
    const order = state.order.filter((n) => n !== name);
    const fav = order.filter((n) => isStarred(state, n));
    const rest = order.filter((n) => !isStarred(state, n));
    if (starred) fav.unshift(name);
    else rest.unshift(name);
    state.order = fav.concat(rest);
    await dbWriteSortOrders(state, state.order);
    syncEph(state);
    await sendMessage(
      chatId,
      "Поднял «" + escapeHtml(name) + "» наверх.",
      { reply_markup: keyboardFor(state) }
    );
    return;
  }

  const name = await ensureList(state, intent.list || DEFAULT_LIST);
  const note = (intent.note || "").trim();
  if (!note) {
    await sendMessage(
      chatId,
      "Не понял текст заметки. Пришлите ещё раз голосом или текстом.",
      { reply_markup: keyboardFor(state) }
    );
    return;
  }
  const newId = await dbInsertNote(state, name, note);
  state.lists[name].push(note);
  state.noteIds[name].push(newId);
  syncEph(state);
  await sendMessage(
    chatId,
    "Добавил в «" + escapeHtml(name) + "»: " + escapeHtml(note),
    { reply_markup: keyboardFor(state) }
  );
}

async function processUserText(chatId, text) {
  if (!groqKey()) {
    await sendMessage(
      chatId,
      "Сервис временно недоступен: не настроен ключ Groq.",
      { reply_markup: await kb(chatId) }
    );
    return;
  }

  let state;
  try {
    state = await loadChat(chatId);
  } catch (err) {
    await sendMessage(chatId, dbFailMessage(err), {
      reply_markup: await kb(chatId),
    });
    return;
  }

  if (state.step === "await_delete_pick" && state.pendingDeletes) {
    const m = String(text || "").trim().match(/^[1-3]$/);
    if (m) {
      const pick = Number(m[0]) - 1;
      const hit = state.pendingDeletes[pick];
      state.step = null;
      state.pendingDeletes = null;
      syncEph(state);
      if (!hit) {
        await sendMessage(chatId, "Нет такого варианта.", {
          reply_markup: keyboardFor(state),
        });
        return;
      }
      const arr = state.lists[hit.list] || [];
      const ids = state.noteIds[hit.list] || [];
      let at = -1;
      if (hit.id != null) {
        at = ids.indexOf(hit.id);
        if (at < 0) at = arr.indexOf(hit.note);
      } else {
        at = arr.indexOf(hit.note);
      }
      if (at < 0) {
        await sendMessage(
          chatId,
          "Эта заметка уже удалена или изменилась.",
          { reply_markup: keyboardFor(state) }
        );
        return;
      }
      try {
        const delId = ids[at] != null ? ids[at] : hit.id;
        if (delId != null) await dbDeleteNoteById(state, delId);
        arr.splice(at, 1);
        ids.splice(at, 1);
      } catch (err) {
        await sendMessage(chatId, dbFailMessage(err), {
          reply_markup: keyboardFor(state),
        });
        return;
      }
      syncEph(state);
      await sendMessage(
        chatId,
        "Удалил из «" +
          escapeHtml(hit.list) +
          "»: " +
          escapeHtml(hit.note),
        { reply_markup: keyboardFor(state) }
      );
      return;
    }
  }

  const deleteHint =
    state.step === "await_delete"
      ? "Пользователь удаляет заметку. Выбери delete_note, delete_last или clear_list."
      : "";
  if (state.step === "await_delete" || state.step === "await_note") {
    state.step = null;
    syncEph(state);
  }

  let intent;
  try {
    intent = await interpret(text, state, deleteHint);
  } catch (_) {
    await sendMessage(
      chatId,
      "Не удалось разобрать сообщение. Попробуйте ещё раз чуть позже.",
      { reply_markup: keyboardFor(state) }
    );
    return;
  }
  try {
    await applyIntent(chatId, state, intent);
  } catch (err) {
    const code = String((err && err.message) || err);
    if (code === "no_supabase" || code.startsWith("supabase_") || code === "name_taken") {
      await sendMessage(chatId, dbFailMessage(err), {
        reply_markup: keyboardFor(state),
      });
      return;
    }
    throw err;
  }
}

async function handleStart(chatId) {
  let state;
  try {
    state = await loadChat(chatId);
  } catch (err) {
    await sendMessage(chatId, dbFailMessage(err));
    return;
  }
  state.step = null;
  state.pendingDeletes = null;
  syncEph(state);
  await sendMessage(
    chatId,
    "Пришлите голосовое или текст.\n" +
      "Примеры: «в покупки купить фильтр», «покажи покупки», «удали молоко из покупок».",
    { reply_markup: keyboardFor(state) }
  );
}

async function handleCancel(chatId) {
  let state;
  try {
    state = await loadChat(chatId);
  } catch (err) {
    await sendMessage(chatId, dbFailMessage(err));
    return;
  }
  state.step = null;
  state.pendingDeletes = null;
  syncEph(state);
  await sendMessage(chatId, "Ок, отменил.", {
    reply_markup: keyboardFor(state),
  });
}

async function handleNewNote(chatId) {
  let state;
  try {
    state = await loadChat(chatId);
  } catch (err) {
    await sendMessage(chatId, dbFailMessage(err));
    return;
  }
  state.step = "await_note";
  state.pendingDeletes = null;
  syncEph(state);
  await sendMessage(
    chatId,
    "Пришлите голосовое или текст для заметки.",
    { reply_markup: keyboardFor(state) }
  );
}

async function handleDeletePrompt(chatId) {
  let state;
  try {
    state = await loadChat(chatId);
  } catch (err) {
    await sendMessage(chatId, dbFailMessage(err));
    return;
  }
  state.step = "await_delete";
  state.pendingDeletes = null;
  syncEph(state);
  await sendMessage(
    chatId,
    "Какую удалить? Можно голосом или текстом: номер, кусок текста или список целиком.",
    { reply_markup: keyboardFor(state) }
  );
}

async function handleShowList(chatId, listName) {
  let state;
  try {
    state = await loadChat(chatId);
  } catch (err) {
    await sendMessage(chatId, dbFailMessage(err));
    return;
  }
  const name = await ensureList(state, listName);
  await showListMessage(chatId, state, name);
}

async function handleCallbackQuery(cq) {
  if (!cq || !cq.message || !cq.message.chat) return;
  const chatId = cq.message.chat.id;
  const data = String(cq.data || "");
  try {
    await tg("answerCallbackQuery", { callback_query_id: cq.id });
  } catch (_) {}
  let state;
  try {
    state = await loadChat(chatId);
  } catch (err) {
    await sendMessage(chatId, dbFailMessage(err));
    return;
  }
  if (!data.startsWith("sn:")) return;
  const idx = Number(data.slice(3));
  const notes = state.lists[DEFAULT_LIST] || [];
  if (!Number.isFinite(idx) || idx < 0 || idx >= notes.length) {
    await sendMessage(chatId, "Этой заметки уже нет.", {
      reply_markup: keyboardFor(state),
    });
    return;
  }
  await sendMessage(chatId, escapeHtml(notes[idx]), {
    reply_markup: keyboardFor(state),
  });
}

async function handleMessage(message) {
  if (!message || !message.chat) return;
  const chatId = message.chat.id;

  if (!token()) {
    return;
  }

  const text = (message.text || "").trim();

  if (isBotCommand(text, "/start")) {
    await handleStart(chatId);
    return;
  }
  if (isBotCommand(text, "/cancel")) {
    await handleCancel(chatId);
    return;
  }
  if (text === NEW_NOTE_BTN) {
    await handleNewNote(chatId);
    return;
  }
  if (text === DELETE_NOTE_BTN) {
    await handleDeletePrompt(chatId);
    return;
  }
  if (text) {
    let state;
    try {
      state = await loadChat(chatId);
    } catch (err) {
      await sendMessage(chatId, dbFailMessage(err));
      return;
    }
    const listHit = resolveListButton(state, text);
    if (listHit) {
      await handleShowList(chatId, listHit);
      return;
    }
  }

  if (message.voice || message.audio) {
    const fileId =
      (message.voice && message.voice.file_id) ||
      (message.audio && message.audio.file_id);
    if (!fileId) return;
    if (!groqKey()) {
      await sendMessage(
        chatId,
        "Сервис временно недоступен: не настроен ключ Groq.",
        { reply_markup: await kb(chatId) }
      );
      return;
    }
    try {
      await sendMessage(chatId, "Слушаю…", {
        reply_markup: await kb(chatId),
      });
      const { buf, filename, mime } = await downloadVoice(fileId);
      const transcript = await transcribe(buf, filename, mime);
      await processUserText(chatId, transcript);
    } catch (err) {
      const code = String((err && err.message) || err);
      let msg;
      if (code === "no_groq") {
        msg = "Сервис временно недоступен: не настроен ключ Groq.";
      } else if (code === "no_supabase" || code.startsWith("supabase_")) {
        msg = dbFailMessage(err);
      } else if (code.startsWith("http_")) {
        msg = "Не удалось обработать голосовое (" + code.slice(5) + ").";
      } else {
        msg = "Не удалось обработать голосовое (" + code + ").";
      }
      await sendMessage(chatId, msg, { reply_markup: await kb(chatId) });
    }
    return;
  }

  if (text) {
    await processUserText(chatId, text);
    return;
  }
}

module.exports = async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(204).end();
  }

  if (req.method === "GET") {
    try {
      if (!token()) {
        return res.status(503).json({
          ok: false,
          error: "TELEGRAM_BOT_TOKEN не задан",
        });
      }
      // Warm schema attempt on GET as well
      try {
        await ensureSchema();
      } catch (_) {}
      const url = webhookPublicUrl();
      const result = await tg("setWebhook", {
        url,
        allowed_updates: ["message", "callback_query"],
        drop_pending_updates: false,
      });
      return res.status(200).json({
        ok: true,
        webhook: url,
        telegram: result,
        hasGroq: Boolean(groqKey()),
        hasSupabase: supabaseConfigured(),
      });
    } catch (err) {
      return res.status(500).json({
        ok: false,
        error: String((err && err.message) || err),
      });
    }
  }

  if (req.method !== "POST") {
    return res.status(405).json({ ok: false, error: "method_not_allowed" });
  }

  if (!token()) {
    return res.status(503).json({ ok: false, error: "no_token" });
  }

  let update = req.body;
  if (typeof update === "string") {
    try {
      update = JSON.parse(update);
    } catch {
      update = {};
    }
  }
  if (!update || typeof update !== "object") update = {};

  try {
    if (update.callback_query) {
      await handleCallbackQuery(update.callback_query);
    } else if (update.message) {
      await handleMessage(update.message);
    }
    return res.status(200).json({ ok: true });
  } catch (err) {
    console.error("bot error", err);
    return res.status(200).json({
      ok: false,
      error: String((err && err.message) || err),
    });
  }
};
